---
- name: "Windows Firewall"
  hosts: all
  gather_facts: true
  become: false
#   vars:
 #   secret_var: "{{ lookup('hashi_vault', 'secret=secret/creds token=s.4YRTM9ChE1JR4mDaDABUsfyZ url=http://54.235.206.14:8200') }}"
  tasks:
    - name: "Set DNS Client"
      win_dns_client:
          adapter_names: Ethernet
          ipv4_addresses:
          - 54.145.133.236
      register: dns_details
    - name: "Join Domain"
      win_domain_membership:
        dns_domain_name: proconnect.local
        hostname: "{{ ansible_hostname }}"
        domain_admin_user: vinayak@proconnect.local 
        domain_admin_password: "{{ lookup('awx.awx.credential_input_source', 'name=ad-vault') }}"
        state: domain
      register: domain_state
    - win_reboot:
      when: domain_state.reboot_required
    - name: Add AD Group
      win_group_membership:
        name: Remote Desktop Users
        members:
           - proconnect\Proconnect-Super-Admin
        state: present

