---
- name: Fetch Secret from Vault
  hosts: localhost
  tasks:
    - name: Fetch Vault Secret
      vars:
        secret_var: "{{ lookup('hashi_vault', 'secret=secret/creds:secret token=proconnect url=http://54.235.206.14:8200')}}"
      debug:
        var: secret_var

    - name: Display Secret
      debug:
        var: secret_var

